project:
  type: website
  output-dir: docs
  render: 
    - index.qmd
    - projects.qmd
    - about.qmd
    - posts/**

website:
  title: "Damini Patel"
  description: "Data Science for Life Science | MCBT @ UNH"
  site-url: "https://daminiunh.github.io/Data_Science_806_Website/"
  favicon: img/favicon.png
  navbar:
    logo: img/favicon.png   # add this file to img/
    background: primary
    search: true
    left:
      - text: Home
        href: index.qmd
      - text: Projects
        href: projects.qmd
      - text: Blog
        href: posts/index.qmd
      - text: About
        href: about.qmd
    right:
      - icon: github
        aria-label: GitHub
        href: "https://github.com/DaminiUNH"
      - icon: envelope
        aria-label: Email
        href: "mailto:Daminiben.Patel@unh.edu"
  page-footer:
    left: "© 2025, Damini Patel"
    right: "Built with [Quarto](https://quarto.org/)"

format:
  html:
    theme:
      light: cosmo     # clean, modern base
      dark: darkly     # matched dark mode
    code-copy: true
    smooth-scroll: true
    toc: false

editor: source